openapi: "3.1.0"
info:
  title: "ARCANA API"
  description: "Backend API for ARCANA — AI Tarot Reading App"
  version: "0.1.0"
servers:
  - url: "http://localhost:8080"
    description: "Local dev"
  - url: "http://194.59.40.207:8080"
    description: "VPS"
paths:
  /health:
    get:
      tags:
        - "System"
      summary: "Health check"
      description: "Returns server status. Use to verify the server is running."
      responses:
        "200":
          description: "Server is healthy"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "ok"