openapi: "3.1.0"
info:
  title: "ARCANA API"
  description: "Backend API for ARCANA — AI Tarot Reading App"
  version: "0.1.0"
servers:
  - url: "http://localhost:8080"
    description: "Local dev"
  - url: "http://194.87.96.68:8080"
    description: "VPS"

components:
  schemas:
    RegisterRequest:
      type: object
      required: [deviceId, platform]
      properties:
        deviceId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        platform:
          type: string
          enum: [android, ios]
          example: "android"

    RefreshRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string
          example: "e3e0ab92-e4d5-4597-81ee-e0b707be02f5"

    TokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIs..."
        refreshToken:
          type: string
          example: "e3e0ab92-e4d5-4597-81ee-e0b707be02f5"

    DailyCardRequest:
      type: object
      required: [cardName, isReversed]
      properties:
        cardName:
          type: string
          example: "The Fool"
        isReversed:
          type: boolean
          example: false
        querentName:
          type: string
          nullable: true
          example: "Nikita"

    DailyCardResponse:
      type: object
      properties:
        readingId:
          type: string
          format: uuid
          example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
        cardName:
          type: string
          example: "The Fool"
        isReversed:
          type: boolean
          example: false
        interpretation:
          type: string
          example: "The Fool speaks of new beginnings..."
        cached:
          type: boolean
          description: "true if this reading was served from today's cache"
          example: false

    ApiError:
      type: object
      properties:
        error:
          type: string
          example: "Invalid refresh token"
        code:
          type: string
          example: "BAD_REQUEST"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /health:
    get:
      tags:
        - "System"
      summary: "Health check"
      description: "Returns server status. Use to verify the server is running."
      responses:
        "200":
          description: "Server is healthy"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "ok"

  /api/v1/auth/register:
    post:
      tags:
        - "Auth"
      summary: "Register device"
      description: "Register a new device or re-authenticate an existing one. Returns access + refresh token pair."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: "Device registered, tokens issued"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: "Invalid request (bad UUID, missing fields)"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /api/v1/auth/refresh:
    post:
      tags:
        - "Auth"
      summary: "Refresh tokens"
      description: "Exchange a valid refresh token for a new access + refresh token pair. Old refresh token is invalidated (rotation)."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        "200":
          description: "New token pair issued"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: "Invalid or expired refresh token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /api/v1/readings/daily:
    post:
      tags:
        - "Daily Card"
      summary: "Get daily card reading"
      description: |
        Generate an AI interpretation for the daily tarot card.
        Returns cached result if already requested today for this device.
        Premium users and Monday free users get a full reading (4-5 paragraphs),
        free users on other days get a brief reading (2-3 paragraphs).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyCardRequest"
      responses:
        "200":
          description: "Daily card interpretation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyCardResponse"
        "401":
          description: "Missing or invalid JWT token"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token is not valid or has expired"
        "503":
          description: "AI service temporarily unavailable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
