package com.schlepping.arcana.tarot.deck

import com.schlepping.arcana.tarot.Suit
import com.schlepping.arcana.tarot.TarotCard

internal val cupsCards: List<TarotCard> = listOf(
    TarotCard(
        id = 22,
        name = "Ace of Cups",
        numeral = "Ace",
        suit = Suit.Cups,
        keywords = listOf("new love", "compassion", "creativity", "emotional fulfillment"),
        uprightMeaning = "An outpouring of love, creativity, or spiritual connection. Open your heart to the new emotional beginnings being offered.",
        reversedMeaning = "Emotional emptiness or blocked feelings. A love opportunity may be missed, or creative inspiration feels stifled.",
    ),
    TarotCard(
        id = 23,
        name = "Two of Cups",
        numeral = "2",
        suit = Suit.Cups,
        keywords = listOf("partnership", "unity", "mutual attraction", "connection"),
        uprightMeaning = "A deep and balanced connection between two souls. Mutual respect and attraction create a harmonious partnership.",
        reversedMeaning = "Imbalance in a relationship or a falling out. Miscommunication and misaligned feelings create distance between partners.",
    ),
    TarotCard(
        id = 24,
        name = "Three of Cups",
        numeral = "3",
        suit = Suit.Cups,
        keywords = listOf("celebration", "friendship", "community", "joy"),
        uprightMeaning = "A time of celebration, friendship, and shared happiness. Gather with those you love and revel in the bonds you share.",
        reversedMeaning = "Overindulgence or gossip within a social circle. Feeling left out or experiencing the downsides of group dynamics.",
    ),
    TarotCard(
        id = 25,
        name = "Four of Cups",
        numeral = "4",
        suit = Suit.Cups,
        keywords = listOf("apathy", "contemplation", "discontent", "missed opportunity"),
        uprightMeaning = "Dissatisfaction and withdrawal from what is offered. Look around — an opportunity may be right in front of you if you open your eyes.",
        reversedMeaning = "Renewed motivation and acceptance of new possibilities. Breaking free from apathy and re-engaging with the world around you.",
    ),
    TarotCard(
        id = 26,
        name = "Five of Cups",
        numeral = "5",
        suit = Suit.Cups,
        keywords = listOf("grief", "loss", "regret", "disappointment"),
        uprightMeaning = "Mourning a loss or dwelling on what went wrong. Acknowledge the pain, but remember that not all is lost — hope remains.",
        reversedMeaning = "Beginning to heal and finding acceptance after grief. Shifting focus from what was lost to the blessings that remain.",
    ),
    TarotCard(
        id = 27,
        name = "Six of Cups",
        numeral = "6",
        suit = Suit.Cups,
        keywords = listOf("nostalgia", "innocence", "reunion", "childhood memories"),
        uprightMeaning = "Sweet memories and connections from the past resurface. Embrace the innocence and joy of simpler times and cherished reunions.",
        reversedMeaning = "Living too much in the past or clinging to outdated memories. Difficulty moving forward due to unresolved childhood experiences.",
    ),
    TarotCard(
        id = 28,
        name = "Seven of Cups",
        numeral = "7",
        suit = Suit.Cups,
        keywords = listOf("illusion", "fantasy", "choices", "wishful thinking"),
        uprightMeaning = "Many options and fantasies cloud your judgement. Discern between dreams and reality to choose a path grounded in truth.",
        reversedMeaning = "Gaining clarity after a period of confusion. Making a committed choice by letting go of unrealistic fantasies.",
    ),
    TarotCard(
        id = 29,
        name = "Eight of Cups",
        numeral = "8",
        suit = Suit.Cups,
        keywords = listOf("departure", "withdrawal", "seeking truth", "disillusionment"),
        uprightMeaning = "Walking away from something that no longer fulfills you. A courageous journey inward to find deeper meaning and purpose.",
        reversedMeaning = "Fear of leaving a familiar but unfulfilling situation. Aimless drifting or returning to something you know you've outgrown.",
    ),
    TarotCard(
        id = 30,
        name = "Nine of Cups",
        numeral = "9",
        suit = Suit.Cups,
        keywords = listOf("contentment", "satisfaction", "wish fulfilled", "gratitude"),
        uprightMeaning = "Your wishes are coming true and deep satisfaction fills your heart. Enjoy this moment of emotional abundance and gratitude.",
        reversedMeaning = "Dissatisfaction despite having much, or superficial happiness. True fulfillment may require looking beyond material comforts.",
    ),
    TarotCard(
        id = 31,
        name = "Ten of Cups",
        numeral = "10",
        suit = Suit.Cups,
        keywords = listOf("harmony", "family", "happiness", "emotional fulfillment"),
        uprightMeaning = "Complete emotional fulfillment and family harmony. Love flows freely and lasting happiness is found in deep, meaningful bonds.",
        reversedMeaning = "Family discord or unrealistic expectations of happiness. The idealized picture of togetherness feels out of reach or superficial.",
    ),
    TarotCard(
        id = 32,
        name = "Page of Cups",
        numeral = "Page",
        suit = Suit.Cups,
        keywords = listOf("creative spark", "intuition", "curiosity", "gentle message"),
        uprightMeaning = "A gentle message of love or creative inspiration arrives. Approach the world with childlike wonder and let your imagination flow.",
        reversedMeaning = "Emotional immaturity or creative blocks. Daydreaming without action or being overly sensitive to criticism.",
    ),
    TarotCard(
        id = 33,
        name = "Knight of Cups",
        numeral = "Knight",
        suit = Suit.Cups,
        keywords = listOf("romance", "charm", "idealism", "following the heart"),
        uprightMeaning = "A romantic and imaginative soul follows their heart. Pursue your dreams with grace and let your emotions guide your quest.",
        reversedMeaning = "Unrealistic expectations in love or moodiness. Charm used for manipulation, or emotions leading to poor decisions.",
    ),
    TarotCard(
        id = 34,
        name = "Queen of Cups",
        numeral = "Queen",
        suit = Suit.Cups,
        keywords = listOf("compassion", "emotional depth", "intuition", "nurturing"),
        uprightMeaning = "Deep compassion and intuitive wisdom guide your interactions. Nurture others from a place of emotional security and empathy.",
        reversedMeaning = "Emotional overwhelm or codependency. Giving too much of yourself to others while neglecting your own emotional needs.",
    ),
    TarotCard(
        id = 35,
        name = "King of Cups",
        numeral = "King",
        suit = Suit.Cups,
        keywords = listOf("emotional mastery", "diplomacy", "calm", "wisdom"),
        uprightMeaning = "Mastery over emotions brings calm and wise leadership. Balance head and heart to navigate complex situations with grace.",
        reversedMeaning = "Emotional manipulation or volatility beneath a calm exterior. Suppressed feelings may erupt, or emotional control becomes repression.",
    ),
)
