package com.schlepping.arcana.tarot.deck

import com.schlepping.arcana.tarot.Suit
import com.schlepping.arcana.tarot.TarotCard

internal val majorArcanaCards: List<TarotCard> = listOf(
    TarotCard(
        id = 0,
        name = "The Fool",
        numeral = "0",
        suit = Suit.MajorArcana,
        keywords = listOf("beginnings", "innocence", "spontaneity", "free spirit"),
        uprightMeaning = "A new beginning full of optimism and potential. Trust in the journey ahead and embrace the unknown with an open heart.",
        reversedMeaning = "Recklessness or fear of the unknown holding you back. Caution against naivety or taking unnecessary risks without thought.",
    ),
    TarotCard(
        id = 1,
        name = "The Magician",
        numeral = "I",
        suit = Suit.MajorArcana,
        keywords = listOf("manifestation", "resourcefulness", "power", "inspired action"),
        uprightMeaning = "You have all the tools and resources you need to manifest your desires. Channel your willpower and take decisive action.",
        reversedMeaning = "Manipulation or trickery may be at play. Talents are being squandered, or there is a disconnect between plans and action.",
    ),
    TarotCard(
        id = 2,
        name = "The High Priestess",
        numeral = "II",
        suit = Suit.MajorArcana,
        keywords = listOf("intuition", "mystery", "subconscious", "inner voice"),
        uprightMeaning = "Trust your intuition and look beyond the surface. Hidden knowledge awaits those who turn inward and listen to their inner wisdom.",
        reversedMeaning = "Secrets or hidden agendas may be causing confusion. You may be ignoring your intuition or feeling disconnected from your inner self.",
    ),
    TarotCard(
        id = 3,
        name = "The Empress",
        numeral = "III",
        suit = Suit.MajorArcana,
        keywords = listOf("abundance", "nurturing", "fertility", "nature"),
        uprightMeaning = "A time of abundance, comfort, and creative growth. Nurture yourself and others, and enjoy the beauty that surrounds you.",
        reversedMeaning = "Creative block or dependence on others for emotional fulfillment. Neglecting self-care or feeling disconnected from nature.",
    ),
    TarotCard(
        id = 4,
        name = "The Emperor",
        numeral = "IV",
        suit = Suit.MajorArcana,
        keywords = listOf("authority", "structure", "stability", "leadership"),
        uprightMeaning = "Establish order and take control of your situation. Strong foundations and disciplined leadership bring lasting success.",
        reversedMeaning = "Excessive control or rigidity is causing problems. Authority may be misused, or there is a lack of discipline and structure.",
    ),
    TarotCard(
        id = 5,
        name = "The Hierophant",
        numeral = "V",
        suit = Suit.MajorArcana,
        keywords = listOf("tradition", "spiritual wisdom", "conformity", "mentorship"),
        uprightMeaning = "Seek guidance from established traditions or a trusted mentor. Spiritual wisdom comes through learning and shared beliefs.",
        reversedMeaning = "Challenging the status quo or feeling restricted by convention. A need to find your own spiritual path beyond established norms.",
    ),
    TarotCard(
        id = 6,
        name = "The Lovers",
        numeral = "VI",
        suit = Suit.MajorArcana,
        keywords = listOf("love", "harmony", "relationships", "choices"),
        uprightMeaning = "A meaningful connection or important choice lies ahead. Align your actions with your values and follow your heart.",
        reversedMeaning = "Disharmony in relationships or inner conflict about a decision. Values may be misaligned, leading to poor choices.",
    ),
    TarotCard(
        id = 7,
        name = "The Chariot",
        numeral = "VII",
        suit = Suit.MajorArcana,
        keywords = listOf("willpower", "determination", "triumph", "control"),
        uprightMeaning = "Victory through sheer determination and focused willpower. Harness opposing forces and charge forward with confidence.",
        reversedMeaning = "Lack of direction or losing control of a situation. Aggression without purpose or being pulled in conflicting directions.",
    ),
    TarotCard(
        id = 8,
        name = "Strength",
        numeral = "VIII",
        suit = Suit.MajorArcana,
        keywords = listOf("courage", "patience", "compassion", "inner strength"),
        uprightMeaning = "True strength comes from patience and compassion, not force. Tame your inner fears with gentle courage and self-mastery.",
        reversedMeaning = "Self-doubt or a lack of inner resolve. Raw emotions may be overwhelming you, or you are avoiding a challenge that requires courage.",
    ),
    TarotCard(
        id = 9,
        name = "The Hermit",
        numeral = "IX",
        suit = Suit.MajorArcana,
        keywords = listOf("introspection", "solitude", "guidance", "soul-searching"),
        uprightMeaning = "Withdraw from the noise and seek answers within. Solitude and deep reflection illuminate the path ahead.",
        reversedMeaning = "Isolation taken too far, or fear of being alone. You may be avoiding necessary self-reflection or withdrawing from those who need you.",
    ),
    TarotCard(
        id = 10,
        name = "Wheel of Fortune",
        numeral = "X",
        suit = Suit.MajorArcana,
        keywords = listOf("cycles", "destiny", "turning point", "luck"),
        uprightMeaning = "The wheel is turning in your favor. Embrace change and trust that the cycles of life are bringing new opportunities.",
        reversedMeaning = "Bad luck or resistance to inevitable change. Feeling stuck in a cycle or unwilling to accept that circumstances are shifting.",
    ),
    TarotCard(
        id = 11,
        name = "Justice",
        numeral = "XI",
        suit = Suit.MajorArcana,
        keywords = listOf("fairness", "truth", "accountability", "law"),
        uprightMeaning = "Truth and fairness will prevail. Take responsibility for your actions and make decisions with integrity and clarity.",
        reversedMeaning = "Injustice or dishonesty is clouding a situation. Avoiding accountability or being treated unfairly by others.",
    ),
    TarotCard(
        id = 12,
        name = "The Hanged Man",
        numeral = "XII",
        suit = Suit.MajorArcana,
        keywords = listOf("surrender", "new perspective", "pause", "letting go"),
        uprightMeaning = "Pause and see things from a different angle. Surrendering control can bring profound insight and spiritual growth.",
        reversedMeaning = "Stalling or refusing to make a necessary sacrifice. Feeling stuck because of an unwillingness to let go or change perspective.",
    ),
    TarotCard(
        id = 13,
        name = "Death",
        numeral = "XIII",
        suit = Suit.MajorArcana,
        keywords = listOf("transformation", "endings", "renewal", "transition"),
        uprightMeaning = "A profound transformation is underway. Let go of what no longer serves you to make room for powerful renewal.",
        reversedMeaning = "Resistance to necessary change or fear of letting go. Stagnation comes from clinging to the past or avoiding transformation.",
    ),
    TarotCard(
        id = 14,
        name = "Temperance",
        numeral = "XIV",
        suit = Suit.MajorArcana,
        keywords = listOf("balance", "moderation", "patience", "harmony"),
        uprightMeaning = "Find your middle ground and practice patience. Blending opposing forces with care creates lasting harmony and healing.",
        reversedMeaning = "Imbalance or excess is disrupting your peace. Impatience or a lack of moderation is leading to conflict and disharmony.",
    ),
    TarotCard(
        id = 15,
        name = "The Devil",
        numeral = "XV",
        suit = Suit.MajorArcana,
        keywords = listOf("shadow self", "attachment", "addiction", "materialism"),
        uprightMeaning = "Examine what binds you — unhealthy attachments or limiting beliefs. Awareness of your shadow is the first step to freedom.",
        reversedMeaning = "Breaking free from addiction or toxic patterns. A moment of clarity that releases you from self-imposed chains.",
    ),
    TarotCard(
        id = 16,
        name = "The Tower",
        numeral = "XVI",
        suit = Suit.MajorArcana,
        keywords = listOf("upheaval", "revelation", "sudden change", "awakening"),
        uprightMeaning = "Sudden upheaval shatters false structures. Though shocking, this destruction clears the way for authentic rebuilding.",
        reversedMeaning = "Averting disaster or resisting necessary upheaval. Fear of change may prolong a situation that needs to crumble.",
    ),
    TarotCard(
        id = 17,
        name = "The Star",
        numeral = "XVII",
        suit = Suit.MajorArcana,
        keywords = listOf("hope", "inspiration", "serenity", "renewal"),
        uprightMeaning = "After the storm comes calm and renewed hope. Trust in the universe and let your inner light guide you toward healing.",
        reversedMeaning = "Loss of faith or feeling uninspired. Disconnection from your sense of purpose or doubting that things will improve.",
    ),
    TarotCard(
        id = 18,
        name = "The Moon",
        numeral = "XVIII",
        suit = Suit.MajorArcana,
        keywords = listOf("illusion", "fear", "subconscious", "intuition"),
        uprightMeaning = "Not everything is as it seems. Navigate through uncertainty by trusting your intuition and facing hidden fears.",
        reversedMeaning = "Clarity emerging from confusion, or repressed emotions surfacing. Releasing anxiety and seeing through previous deceptions.",
    ),
    TarotCard(
        id = 19,
        name = "The Sun",
        numeral = "XIX",
        suit = Suit.MajorArcana,
        keywords = listOf("joy", "success", "vitality", "positivity"),
        uprightMeaning = "Radiant joy, success, and vitality surround you. Embrace this bright energy and share your warmth with the world.",
        reversedMeaning = "Temporary sadness or dampened enthusiasm. The inner child feels blocked, or success is delayed but not denied.",
    ),
    TarotCard(
        id = 20,
        name = "Judgement",
        numeral = "XX",
        suit = Suit.MajorArcana,
        keywords = listOf("rebirth", "reflection", "reckoning", "absolution"),
        uprightMeaning = "A powerful moment of self-evaluation and rebirth. Answer the call to rise, release the past, and step into your higher purpose.",
        reversedMeaning = "Self-doubt or refusal to learn from past experiences. Avoiding a necessary reckoning or being too harsh in self-judgement.",
    ),
    TarotCard(
        id = 21,
        name = "The World",
        numeral = "XXI",
        suit = Suit.MajorArcana,
        keywords = listOf("completion", "wholeness", "achievement", "fulfillment"),
        uprightMeaning = "A cycle reaches its glorious completion. Celebrate your achievements and the wholeness you have attained before a new journey begins.",
        reversedMeaning = "Feeling incomplete or falling short of a goal. A journey is delayed, or there is a reluctance to bring closure to an important chapter.",
    ),
)
