package com.schlepping.arcana.tarot.deck

import com.schlepping.arcana.tarot.Suit
import com.schlepping.arcana.tarot.TarotCard

internal val pentaclesCards: List<TarotCard> = listOf(
    TarotCard(
        id = 64,
        name = "Ace of Pentacles",
        numeral = "Ace",
        suit = Suit.Pentacles,
        keywords = listOf("opportunity", "prosperity", "new venture", "manifestation"),
        uprightMeaning = "A golden opportunity for prosperity and material growth appears. Plant the seeds of this new venture with care and watch abundance grow.",
        reversedMeaning = "A missed financial opportunity or poor planning. Resources are wasted, or a promising venture fails to materialize.",
    ),
    TarotCard(
        id = 65,
        name = "Two of Pentacles",
        numeral = "2",
        suit = Suit.Pentacles,
        keywords = listOf("balance", "adaptability", "juggling priorities", "flexibility"),
        uprightMeaning = "Skillfully balancing multiple responsibilities with grace. Stay adaptable and flexible as you juggle the demands of daily life.",
        reversedMeaning = "Overwhelm from trying to manage too much at once. Dropping the ball on important commitments or financial disorganization.",
    ),
    TarotCard(
        id = 66,
        name = "Three of Pentacles",
        numeral = "3",
        suit = Suit.Pentacles,
        keywords = listOf("teamwork", "collaboration", "craftsmanship", "skill"),
        uprightMeaning = "Skilled collaboration produces work of lasting quality. Your expertise is valued — contribute your talents to a shared vision.",
        reversedMeaning = "Lack of teamwork or poor workmanship. Misaligned goals within a group, or individual effort goes unrecognized.",
    ),
    TarotCard(
        id = 67,
        name = "Four of Pentacles",
        numeral = "4",
        suit = Suit.Pentacles,
        keywords = listOf("security", "control", "possessiveness", "conservation"),
        uprightMeaning = "Holding tightly to what you have built provides security. Be mindful that protecting resources does not become fearful hoarding.",
        reversedMeaning = "Letting go of material attachment or financial insecurity. Either generous release or reckless spending disrupts stability.",
    ),
    TarotCard(
        id = 68,
        name = "Five of Pentacles",
        numeral = "5",
        suit = Suit.Pentacles,
        keywords = listOf("hardship", "isolation", "worry", "financial loss"),
        uprightMeaning = "A period of material hardship or feeling left out in the cold. Help is closer than you think — do not let pride prevent you from seeking support.",
        reversedMeaning = "Recovery from financial difficulty or finding spiritual wealth. The worst is passing, and new sources of support are emerging.",
    ),
    TarotCard(
        id = 69,
        name = "Six of Pentacles",
        numeral = "6",
        suit = Suit.Pentacles,
        keywords = listOf("generosity", "charity", "sharing", "reciprocity"),
        uprightMeaning = "Generosity flows in both directions — give and receive with an open heart. Sharing your resources creates a cycle of abundance.",
        reversedMeaning = "Strings attached to generosity or imbalance in giving. One-sided charity that creates dependency rather than empowerment.",
    ),
    TarotCard(
        id = 70,
        name = "Seven of Pentacles",
        numeral = "7",
        suit = Suit.Pentacles,
        keywords = listOf("patience", "investment", "long-term view", "assessment"),
        uprightMeaning = "Patience is rewarded as long-term investments begin to bear fruit. Assess your progress and trust that steady effort yields results.",
        reversedMeaning = "Impatience with slow results or poor return on investment. Questioning whether your efforts have been worthwhile.",
    ),
    TarotCard(
        id = 71,
        name = "Eight of Pentacles",
        numeral = "8",
        suit = Suit.Pentacles,
        keywords = listOf("diligence", "mastery", "skill development", "dedication"),
        uprightMeaning = "Dedicated practice and attention to detail hone your craft. Commit to mastery through patient, focused effort and continuous learning.",
        reversedMeaning = "Perfectionism, monotony, or lack of motivation. Cutting corners on quality or feeling uninspired by repetitive work.",
    ),
    TarotCard(
        id = 72,
        name = "Nine of Pentacles",
        numeral = "9",
        suit = Suit.Pentacles,
        keywords = listOf("luxury", "self-sufficiency", "independence", "refinement"),
        uprightMeaning = "Enjoy the rewards of your hard work and self-reliance. Luxury and independence are yours — savor this well-earned abundance.",
        reversedMeaning = "Overindulgence or financial setbacks threatening independence. Self-worth tied too closely to material possessions.",
    ),
    TarotCard(
        id = 73,
        name = "Ten of Pentacles",
        numeral = "10",
        suit = Suit.Pentacles,
        keywords = listOf("legacy", "wealth", "family", "long-term success"),
        uprightMeaning = "Lasting wealth and a legacy of security surround you. Family bonds and inherited wisdom form a foundation of enduring prosperity.",
        reversedMeaning = "Family financial disputes or a legacy under threat. Short-term thinking undermines long-term security and generational wealth.",
    ),
    TarotCard(
        id = 74,
        name = "Page of Pentacles",
        numeral = "Page",
        suit = Suit.Pentacles,
        keywords = listOf("ambition", "studiousness", "new opportunity", "diligence"),
        uprightMeaning = "A studious and ambitious spirit embarks on a practical new goal. Approach this opportunity with diligence and a desire to learn.",
        reversedMeaning = "Lack of focus or procrastination on important goals. A promising opportunity is neglected due to laziness or distraction.",
    ),
    TarotCard(
        id = 75,
        name = "Knight of Pentacles",
        numeral = "Knight",
        suit = Suit.Pentacles,
        keywords = listOf("reliability", "hard work", "routine", "methodical progress"),
        uprightMeaning = "Steady, reliable effort moves you methodically toward your goal. Patience and routine may lack glamour, but they deliver lasting results.",
        reversedMeaning = "Stagnation, laziness, or being stuck in a rut. Methodical becomes monotonous, or perfectionism prevents any progress.",
    ),
    TarotCard(
        id = 76,
        name = "Queen of Pentacles",
        numeral = "Queen",
        suit = Suit.Pentacles,
        keywords = listOf("nurturing abundance", "practicality", "comfort", "generosity"),
        uprightMeaning = "Practical wisdom and nurturing generosity create a warm, abundant home. Care for others and yourself with grounded, earthy grace.",
        reversedMeaning = "Neglecting self-care while caring for others, or material obsession. Smothering with generosity or losing touch with practical needs.",
    ),
    TarotCard(
        id = 77,
        name = "King of Pentacles",
        numeral = "King",
        suit = Suit.Pentacles,
        keywords = listOf("wealth", "business acumen", "stability", "discipline"),
        uprightMeaning = "Mastery over the material world through discipline and sound judgement. Your steady leadership builds lasting wealth and security for all.",
        reversedMeaning = "Greed, materialism, or financial mismanagement. Using wealth as power over others, or stability crumbling due to poor decisions.",
    ),
)
