package com.schlepping.arcana.tarot.deck

import com.schlepping.arcana.tarot.Suit
import com.schlepping.arcana.tarot.TarotCard

internal val swordsCards: List<TarotCard> = listOf(
    TarotCard(
        id = 36,
        name = "Ace of Swords",
        numeral = "Ace",
        suit = Suit.Swords,
        keywords = listOf("clarity", "breakthrough", "truth", "new idea"),
        uprightMeaning = "A breakthrough of clarity and truth cuts through confusion. Seize this moment of mental power to pursue a new vision.",
        reversedMeaning = "Confusion or misuse of intellect. A great idea lacks follow-through, or the truth is being distorted.",
    ),
    TarotCard(
        id = 37,
        name = "Two of Swords",
        numeral = "2",
        suit = Suit.Swords,
        keywords = listOf("indecision", "stalemate", "avoidance", "difficult choice"),
        uprightMeaning = "A difficult decision weighs on you and neither option feels clear. Remove the blindfold and face the facts to move forward.",
        reversedMeaning = "Information comes to light that breaks a stalemate. The truth can no longer be avoided, forcing a necessary decision.",
    ),
    TarotCard(
        id = 38,
        name = "Three of Swords",
        numeral = "3",
        suit = Suit.Swords,
        keywords = listOf("heartbreak", "grief", "sorrow", "painful truth"),
        uprightMeaning = "A painful truth or heartbreak must be acknowledged. Allow yourself to grieve — healing begins with honest acceptance of pain.",
        reversedMeaning = "Beginning to recover from heartbreak or releasing deep sorrow. Forgiveness and emotional healing are slowly taking root.",
    ),
    TarotCard(
        id = 39,
        name = "Four of Swords",
        numeral = "4",
        suit = Suit.Swords,
        keywords = listOf("rest", "recovery", "contemplation", "retreat"),
        uprightMeaning = "Step back and allow yourself to rest and recover. Quiet contemplation and retreat restore your mental strength for challenges ahead.",
        reversedMeaning = "Restlessness or burnout from refusing to slow down. Being forced to rest, or anxiety preventing the peace you need.",
    ),
    TarotCard(
        id = 40,
        name = "Five of Swords",
        numeral = "5",
        suit = Suit.Swords,
        keywords = listOf("conflict", "defeat", "winning at a cost", "hostility"),
        uprightMeaning = "A hollow victory or painful conflict where no one truly wins. Consider whether the battle is worth the cost to all involved.",
        reversedMeaning = "Reconciliation after conflict or learning from defeat. Choosing to walk away from a fight that serves no one.",
    ),
    TarotCard(
        id = 41,
        name = "Six of Swords",
        numeral = "6",
        suit = Suit.Swords,
        keywords = listOf("transition", "moving on", "healing journey", "calmer waters"),
        uprightMeaning = "Leaving troubled waters behind for a calmer shore. This transition may be bittersweet, but it leads to necessary healing.",
        reversedMeaning = "Difficulty moving on from a painful situation. Feeling stuck or unable to leave behind emotional baggage.",
    ),
    TarotCard(
        id = 42,
        name = "Seven of Swords",
        numeral = "7",
        suit = Suit.Swords,
        keywords = listOf("deception", "strategy", "stealth", "cunning"),
        uprightMeaning = "Strategic thinking is required, but beware of deception — from others or yourself. Not everything is being done in the open.",
        reversedMeaning = "Secrets being revealed or a confession coming to light. A deceptive plan unravels, or you choose honesty over cunning.",
    ),
    TarotCard(
        id = 43,
        name = "Eight of Swords",
        numeral = "8",
        suit = Suit.Swords,
        keywords = listOf("restriction", "trapped", "self-limiting beliefs", "helplessness"),
        uprightMeaning = "You feel trapped, but the bonds are largely of your own making. Shift your perspective to see the freedom that already exists.",
        reversedMeaning = "Breaking free from mental limitations and self-imposed restrictions. A new perspective reveals that escape was always possible.",
    ),
    TarotCard(
        id = 44,
        name = "Nine of Swords",
        numeral = "9",
        suit = Suit.Swords,
        keywords = listOf("anxiety", "nightmares", "worry", "despair"),
        uprightMeaning = "Anxiety and worry keep you awake at night. Much of the fear may be worse than reality — reach out for support and perspective.",
        reversedMeaning = "Finding hope after a dark period or releasing deep-seated anxiety. Learning to manage worry and reclaim peace of mind.",
    ),
    TarotCard(
        id = 45,
        name = "Ten of Swords",
        numeral = "10",
        suit = Suit.Swords,
        keywords = listOf("rock bottom", "ending", "betrayal", "inevitable conclusion"),
        uprightMeaning = "A painful ending has been reached — the worst is over. From this lowest point, the only direction is up toward renewal.",
        reversedMeaning = "Surviving a crisis and beginning to recover. Resisting the final blow, or slowly rising after hitting rock bottom.",
    ),
    TarotCard(
        id = 46,
        name = "Page of Swords",
        numeral = "Page",
        suit = Suit.Swords,
        keywords = listOf("curiosity", "restlessness", "new ideas", "vigilance"),
        uprightMeaning = "A curious and alert mind eager to learn and communicate. Stay vigilant and channel your mental energy into constructive pursuits.",
        reversedMeaning = "Gossip, hasty words, or scattered thinking. All talk and no action, or using sharp words carelessly.",
    ),
    TarotCard(
        id = 47,
        name = "Knight of Swords",
        numeral = "Knight",
        suit = Suit.Swords,
        keywords = listOf("ambition", "action", "drive", "swift change"),
        uprightMeaning = "Charging forward with fierce determination and intellectual clarity. Be bold in pursuit of truth, but temper speed with wisdom.",
        reversedMeaning = "Reckless haste or aggression without direction. Rushing into situations without thinking through the consequences.",
    ),
    TarotCard(
        id = 48,
        name = "Queen of Swords",
        numeral = "Queen",
        suit = Suit.Swords,
        keywords = listOf("independence", "perception", "clear boundaries", "direct communication"),
        uprightMeaning = "Sharp perception and honest communication cut to the heart of any matter. Set clear boundaries with intelligence and grace.",
        reversedMeaning = "Coldness or cruelty masked as honesty. Overly critical judgement or using intellect to keep others at a distance.",
    ),
    TarotCard(
        id = 49,
        name = "King of Swords",
        numeral = "King",
        suit = Suit.Swords,
        keywords = listOf("intellectual authority", "truth", "ethical leadership", "clear thinking"),
        uprightMeaning = "Lead with clarity, fairness, and intellectual authority. Sound judgement and ethical reasoning guide you to wise decisions.",
        reversedMeaning = "Tyrannical use of intellect or manipulative reasoning. Cold authority without compassion, or abusing a position of power.",
    ),
)
