package com.schlepping.arcana.tarot.deck

import com.schlepping.arcana.tarot.Suit
import com.schlepping.arcana.tarot.TarotCard

internal val wandsCards: List<TarotCard> = listOf(
    TarotCard(
        id = 50,
        name = "Ace of Wands",
        numeral = "Ace",
        suit = Suit.Wands,
        keywords = listOf("inspiration", "new venture", "creative spark", "potential"),
        uprightMeaning = "A bold spark of inspiration ignites a new creative venture. Seize this surge of energy and passion to begin something meaningful.",
        reversedMeaning = "Delays in starting a new project or lack of motivation. Creative energy is present but blocked or misdirected.",
    ),
    TarotCard(
        id = 51,
        name = "Two of Wands",
        numeral = "2",
        suit = Suit.Wands,
        keywords = listOf("planning", "future vision", "decisions", "discovery"),
        uprightMeaning = "The world is in your hands as you plan your next bold move. Envision the future you desire and take the first steps toward it.",
        reversedMeaning = "Fear of the unknown or lack of planning. Staying in your comfort zone instead of pursuing a bigger vision.",
    ),
    TarotCard(
        id = 52,
        name = "Three of Wands",
        numeral = "3",
        suit = Suit.Wands,
        keywords = listOf("expansion", "foresight", "progress", "opportunity"),
        uprightMeaning = "Your plans are taking shape and opportunities expand before you. Look to the horizon with confidence as progress unfolds.",
        reversedMeaning = "Delays in progress or frustration with obstacles. Plans may not be unfolding as expected, requiring patience and adjustment.",
    ),
    TarotCard(
        id = 53,
        name = "Four of Wands",
        numeral = "4",
        suit = Suit.Wands,
        keywords = listOf("celebration", "homecoming", "harmony", "milestone"),
        uprightMeaning = "A joyful celebration marks a milestone achieved. Enjoy this moment of stability, harmony, and community togetherness.",
        reversedMeaning = "Feeling unwelcome or experiencing instability at home. A celebration is dampened, or a milestone feels incomplete.",
    ),
    TarotCard(
        id = 54,
        name = "Five of Wands",
        numeral = "5",
        suit = Suit.Wands,
        keywords = listOf("competition", "conflict", "tension", "diversity of opinion"),
        uprightMeaning = "Healthy competition and lively debate push you to grow. Channel this tension creatively rather than letting it become destructive.",
        reversedMeaning = "Avoiding conflict at all costs or inner turmoil. Competition turns petty, or disagreements are swept under the rug.",
    ),
    TarotCard(
        id = 55,
        name = "Six of Wands",
        numeral = "6",
        suit = Suit.Wands,
        keywords = listOf("victory", "recognition", "pride", "public acclaim"),
        uprightMeaning = "Public recognition and triumph crown your efforts. Enjoy this well-earned victory and let it fuel your continued momentum.",
        reversedMeaning = "Ego or arrogance after success, or a fall from grace. Seeking validation externally rather than finding inner confidence.",
    ),
    TarotCard(
        id = 56,
        name = "Seven of Wands",
        numeral = "7",
        suit = Suit.Wands,
        keywords = listOf("perseverance", "defense", "standing ground", "challenge"),
        uprightMeaning = "Stand your ground and defend what you believe in. Challenges test your resolve, but perseverance will see you through.",
        reversedMeaning = "Feeling overwhelmed by opposition or giving up too easily. Exhaustion from constant battles or losing your competitive edge.",
    ),
    TarotCard(
        id = 57,
        name = "Eight of Wands",
        numeral = "8",
        suit = Suit.Wands,
        keywords = listOf("swift action", "momentum", "rapid progress", "movement"),
        uprightMeaning = "Events accelerate and things fall into place rapidly. Ride this wave of momentum and act decisively while the energy flows.",
        reversedMeaning = "Delays, frustration, or scattered energy. Plans stall or messages are miscommunicated, causing confusion.",
    ),
    TarotCard(
        id = 58,
        name = "Nine of Wands",
        numeral = "9",
        suit = Suit.Wands,
        keywords = listOf("resilience", "persistence", "courage", "last stand"),
        uprightMeaning = "You have been through much, but your resilience carries you forward. Summon your remaining strength — the finish line is near.",
        reversedMeaning = "Stubbornness or paranoia after too many battles. Exhaustion makes it hard to trust, or defenses are too rigid.",
    ),
    TarotCard(
        id = 59,
        name = "Ten of Wands",
        numeral = "10",
        suit = Suit.Wands,
        keywords = listOf("burden", "responsibility", "overcommitment", "hard work"),
        uprightMeaning = "The weight of heavy burdens and responsibilities presses down. Delegate or release what you can before reaching your breaking point.",
        reversedMeaning = "Learning to delegate or finally putting down a heavy burden. The realization that you do not have to carry everything alone.",
    ),
    TarotCard(
        id = 60,
        name = "Page of Wands",
        numeral = "Page",
        suit = Suit.Wands,
        keywords = listOf("enthusiasm", "exploration", "discovery", "free spirit"),
        uprightMeaning = "Boundless enthusiasm and a taste for adventure fuel new discoveries. Follow your curiosity and let your passions lead the way.",
        reversedMeaning = "Lack of direction or hesitation to start. Enthusiasm fizzles out quickly, or restlessness prevents follow-through.",
    ),
    TarotCard(
        id = 61,
        name = "Knight of Wands",
        numeral = "Knight",
        suit = Suit.Wands,
        keywords = listOf("energy", "passion", "adventure", "impulsiveness"),
        uprightMeaning = "Fiery passion and fearless energy charge into action. Pursue your goals with boldness, but channel your fire with purpose.",
        reversedMeaning = "Impulsiveness or burnout from reckless action. Energy is scattered, or frustration arises from delays and obstacles.",
    ),
    TarotCard(
        id = 62,
        name = "Queen of Wands",
        numeral = "Queen",
        suit = Suit.Wands,
        keywords = listOf("confidence", "warmth", "determination", "vibrancy"),
        uprightMeaning = "Radiant confidence and warm determination inspire everyone around you. Lead with passion and let your vibrant energy light the way.",
        reversedMeaning = "Jealousy, selfishness, or demanding nature. Confidence turns to arrogance, or warmth is withheld as a form of control.",
    ),
    TarotCard(
        id = 63,
        name = "King of Wands",
        numeral = "King",
        suit = Suit.Wands,
        keywords = listOf("visionary leadership", "boldness", "entrepreneurship", "honor"),
        uprightMeaning = "A bold visionary who leads with charisma and honor. Your entrepreneurial spirit and natural authority inspire others to follow.",
        reversedMeaning = "Overbearing leadership or setting unrealistic expectations. Impulsiveness in decision-making or using authority recklessly.",
    ),
)
